spring.application.name=email



server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5432/ms-email
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.format_sql=true

spring.rabbitmq.addresses=amqps://qjeknafj:BH8z1oIOqgzjmXu3lZX6CFocbOz4avYm@jackal.rmq.cloudamqp.com/qjeknafj

broker.queue.email.name=default.email